apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topic
spec:
  template:
    spec:
      containers:
      - name: kafka-admin
        image: confluentinc/cp-kafka:7.4.0
        command: ["/bin/sh", "-c"]
        args:
          - kafka-topics --create --topic locations --bootstrap-server kafka-service:9092 --partitions 3 --replication-factor 1;
      restartPolicy: Never
